py34

diff --git a/.github/workflows/ci_pr.yml b/.github/workflows/ci_pr.yml
--- a/.github/workflows/ci_pr.yml
+++ b/.github/workflows/ci_pr.yml
@@ -9,8 +9,15 @@ on:
 
 jobs:
   test-legacy-python-versions:
-    
-    name: "Python 2.6 Unit Tests"
+
+    strategy:
+      fail-fast: false
+      matrix:
+        include:
+          - python-version: 2.6
+          - python-version: 3.4
+
+    name: "Python ${{ matrix.python-version }} Unit Tests"
     runs-on: ubuntu-20.04
     container:
       image: ubuntu:16.04
@@ -20,100 +27,137 @@ jobs:
       run:
         shell: bash -l {0}
 
-    strategy:
-      fail-fast: false
     env:
       NOSEOPTS: "--verbose"
 
     steps:
     - uses: actions/checkout@v3
 
-    - name: Install Python 2.6
+    - name: Install Python ${{ matrix.python-version }}
       run: |
         apt-get update
         apt-get install -y curl bzip2 sudo python3
-        curl https://dcrdata.blob.core.windows.net/python/python-2.6.tar.bz2 -o python-2.6.tar.bz2
-        sudo tar xjvf python-2.6.tar.bz2 --directory /
+        curl https://dcrdata.blob.core.windows.net/python/python-${{ matrix.python-version }}.tar.bz2 -o python-${{ matrix.python-version }}.tar.bz2
+        sudo tar xjvf python-${{ matrix.python-version }}.tar.bz2 --directory /
 
     - name: Test with nosetests
       run: |
-        source /home/waagent/virtualenv/python2.6.9/bin/activate
+        if [[ ${{ matrix.python-version }} == 2.6 ]]; then
+          source /home/waagent/virtualenv/python2.6.9/bin/activate
+        else
+          source /home/waagent/virtualenv/python3.4.8/bin/activate
+        fi
         ./ci/nosetests.sh
         exit $?
 
-  test-current-python-versions:
+#  test-legacy-python34:
+#
+#    name: "Python 3.4 Unit Tests"
+#    runs-on: ubuntu-20.04
+#    container:
+#      image: ubuntu:16.04
+#      volumes:
+#        - /home/waagent:/home/waagent
+#    defaults:
+#      run:
+#        shell: bash -l {0}
+#
+#    strategy:
+#      fail-fast: false
+#    env:
+#      NOSEOPTS: "--verbose"
+#
+#    steps:
+#    - uses: actions/checkout@v3
+#
+#    - name: Install Python 3.4
+#      run: |
+#        apt-get update
+#        apt-get install -y curl bzip2 sudo python3 iproute2
+#        curl https://dcrdata.blob.core.windows.net/python/python-3.4.tar.bz2 -o python-3.4.tar.bz2
+#        sudo tar xvf python-3.4.tar.bz2 --directory /
+#
+#    - name: Test with nosetests
+#      run: |
+#        source /home/waagent/venv/python3.4.8/bin/activate
+#        pip install -r requirements.txt
+#        pip install -r test-requirements.txt
+#        ./ci/nosetests.sh
+#        exit $?
 
-    strategy:
-      fail-fast: false
-      matrix:
-        include:
-
-          - python-version: 2.7
-            PYLINTOPTS: "--rcfile=ci/2.7.pylintrc --ignore=tests_e2e,makepkg.py"
-
-          - python-version: 3.5
-            PYLINTOPTS: "--rcfile=ci/3.6.pylintrc --ignore=tests_e2e,makepkg.py"
-
-          - python-version: 3.6
-            PYLINTOPTS: "--rcfile=ci/3.6.pylintrc --ignore=tests_e2e"
-
-          - python-version: 3.7
-            PYLINTOPTS: "--rcfile=ci/3.6.pylintrc --ignore=tests_e2e"
-
-          - python-version: 3.8
-            PYLINTOPTS: "--rcfile=ci/3.6.pylintrc --ignore=tests_e2e"
-
-          - python-version: 3.9
-            PYLINTOPTS: "--rcfile=ci/3.6.pylintrc"
-            additional-nose-opts: "--with-coverage --cover-erase --cover-inclusive --cover-branches --cover-package=azurelinuxagent"
-
-    name: "Python ${{ matrix.python-version }} Unit Tests"
-    runs-on: ubuntu-20.04
-
-    env:
-      PYLINTOPTS: ${{ matrix.PYLINTOPTS }}
-      PYLINTFILES: "azurelinuxagent setup.py makepkg.py tests tests_e2e"
-      NOSEOPTS: "--with-timer ${{ matrix.additional-nose-opts }}"
-      PYTHON_VERSION: ${{ matrix.python-version }}
-
-    steps:
-
-    - name: Checkout WALinuxAgent repo
-      uses: actions/checkout@v3
-
-    - name: Setup Python ${{ matrix.python-version }}
-      uses: actions/setup-python@v4
-      with:
-        python-version: ${{ matrix.python-version }}
-
-    - name: Install dependencies
-      id: install-dependencies
-      run: |
-        sudo env "PATH=$PATH" python -m pip install --upgrade pip
-        sudo env "PATH=$PATH" pip install -r requirements.txt
-        sudo env "PATH=$PATH" pip install -r test-requirements.txt
-
-    - name: Run pylint
-      run: |
-        pylint $PYLINTOPTS --jobs=0 $PYLINTFILES
-
-    - name: Test with nosetests
-      if: success() || (failure() && steps.install-dependencies.outcome == 'success')
-      run: |
-        ./ci/nosetests.sh
-        exit $?
-
-    - name: Compile Coverage
-      if: matrix.python-version == 3.9
-      run: |
-        echo looking for coverage files :
-        ls -alh | grep -i coverage
-        sudo env "PATH=$PATH" coverage combine coverage.*.data
-        sudo env "PATH=$PATH" coverage xml
-        sudo env "PATH=$PATH" coverage report
-
-    - name: Upload Coverage
-      if: matrix.python-version == 3.9
-      uses: codecov/codecov-action@v2
-      with:
-        file: ./coverage.xml
+#  test-current-python-versions:
+#
+#    strategy:
+#      fail-fast: false
+#      matrix:
+#        include:
+#
+#          - python-version: 2.7
+#            PYLINTOPTS: "--rcfile=ci/2.7.pylintrc --ignore=tests_e2e,makepkg.py"
+#
+#          - python-version: 3.5
+#            PYLINTOPTS: "--rcfile=ci/3.6.pylintrc --ignore=tests_e2e,makepkg.py"
+#
+#          - python-version: 3.6
+#            PYLINTOPTS: "--rcfile=ci/3.6.pylintrc --ignore=tests_e2e"
+#
+#          - python-version: 3.7
+#            PYLINTOPTS: "--rcfile=ci/3.6.pylintrc --ignore=tests_e2e"
+#
+#          - python-version: 3.8
+#            PYLINTOPTS: "--rcfile=ci/3.6.pylintrc --ignore=tests_e2e"
+#
+#          - python-version: 3.9
+#            PYLINTOPTS: "--rcfile=ci/3.6.pylintrc"
+#            additional-nose-opts: "--with-coverage --cover-erase --cover-inclusive --cover-branches --cover-package=azurelinuxagent"
+#
+#    name: "Python ${{ matrix.python-version }} Unit Tests"
+#    runs-on: ubuntu-20.04
+#
+#    env:
+#      PYLINTOPTS: ${{ matrix.PYLINTOPTS }}
+#      PYLINTFILES: "azurelinuxagent setup.py makepkg.py tests tests_e2e"
+#      NOSEOPTS: "--with-timer ${{ matrix.additional-nose-opts }}"
+#      PYTHON_VERSION: ${{ matrix.python-version }}
+#
+#    steps:
+#
+#    - name: Checkout WALinuxAgent repo
+#      uses: actions/checkout@v3
+#
+#    - name: Setup Python ${{ matrix.python-version }}
+#      uses: actions/setup-python@v4
+#      with:
+#        python-version: ${{ matrix.python-version }}
+#
+#    - name: Install dependencies
+#      id: install-dependencies
+#      run: |
+#        sudo env "PATH=$PATH" python -m pip install --upgrade pip
+#        sudo env "PATH=$PATH" pip install -r requirements.txt
+#        sudo env "PATH=$PATH" pip install -r test-requirements.txt
+#
+#    - name: Run pylint
+#      run: |
+#        pylint $PYLINTOPTS --jobs=0 $PYLINTFILES
+#
+#    - name: Test with nosetests
+#      if: success() || (failure() && steps.install-dependencies.outcome == 'success')
+#      run: |
+#        ./ci/nosetests.sh
+#        exit $?
+#
+#    - name: Compile Coverage
+#      if: matrix.python-version == 3.9
+#      run: |
+#        echo looking for coverage files :
+#        ls -alh | grep -i coverage
+#        sudo env "PATH=$PATH" coverage combine coverage.*.data
+#        sudo env "PATH=$PATH" coverage xml
+#        sudo env "PATH=$PATH" coverage report
+#
+#    - name: Upload Coverage
+#      if: matrix.python-version == 3.9
+#      uses: codecov/codecov-action@v2
+#      with:
+#        file: ./coverage.xml
